sudo: required

services:
  - docker

before_install:
  - docker build -t theDebofNight19/docker-react -f Dockerfile.dev .

script:
  - docker run theDebofNight19/docker-react npm run test -- --coverage